//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// user_discusssubclass_add 类。
/// </summary>
/// <remarks>
/// 自动生成的类。
/// </remarks>
public partial class user_discusssubclass_add {
    
    /// <summary>
    /// form1 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// ClassIDList1 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ClassIDList1;
    
    /// <summary>
    /// Cname 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox Cname;
    
    /// <summary>
    /// RequiredFieldValidator3 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
    
    /// <summary>
    /// Content 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox Content;
    
    /// <summary>
    /// RequiredFieldValidator2 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
    
    /// <summary>
    /// but1 控件。
    /// </summary>
    /// <remarks>
    /// 自动生成的字段。
    /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button but1;
}
