insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('sysParam01','系统参数设置导航帮助','系统参数设置导航帮助。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_shortcut_0001','快捷方式名称','菜单显示名称，最大允许20个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_shortcut_0002','快捷方式连接路径','菜单连接的页面地址，此页面将在sys_main窗口中打开。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_shortcut_0003','排列序号','菜单在导航中的显示位置。数字越大，排列越前。只允许填写正整数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_shortcut_0004','如何使用快捷方式','只要您创建了快捷方式。你可以点击页面最上的导航条<font color=blue>[快捷方式]</font>，迅速找到您需要的功能操作连接！<br>同时，在每个大功能的左边窗体也有收缩起来的快捷菜单。扩展菜单，就可以迅速找到你需要的连接。<br /><font color=red>特别提醒：最多允许创建20个快捷方式。</font> ');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Db_001','执行SQL语句','不能为空，一次只能执行一条Sql语句。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Db_002','数据库备份','请在备份完成后，及时删除备份文件，以防止别人恶意下载数据库文件。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Db_003','压缩数据库','(只针对Access数据库)可以优化一下数据库，压缩前请备份您的数据库，以防止万一。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0003','位置标识','长度为5位，如果为00000则放到顶部；如果为 99999则存放到[API管理]中的下拉菜单中；如果为其他数据，则存放到左侧导航菜单中<br><font color=red>特别提醒：如果不指定父菜单，则此项必须填写00000或者999999</font><br /><font color=blue>强烈建议：顶部最多建议放8个菜单，否则会变形。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0005','系统菜单','如果为系统菜单，不能删除。只能修改排列顺序及名称，其他参数不允许修改。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0004','显示类型','菜单显示在用户管理中心前台还是管理员管理后台。默认为显示在管理员管理后台。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0002','父菜单','菜单的父级菜单，只允许最多5级。<br /><font color=red>强烈建议：顶部最多建议放8个菜单。否则会变形。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0001','菜单名称','菜单名称，最大长度为20，建议长度范围为3-5。这样可以是页面更加美观。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0008','打开窗口方式','菜单连接文件的打开窗口。<br />如果要在左窗口打开，请用menu，如果要在主窗口中打开，请使用sys_main。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0007','排列序号','菜单在导航中的显示位置。数字越小，排列越前。只允许填写正整数。范围为0-99。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_0006','快捷菜单路径','快捷菜单连接路径，长度为200字节。如果是在本地目录，请使用相对于manage的路径。<br /><font color=red>提醒：如果存放到顶部或者API下拉菜单中，则不设置此路径。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_news__0001','栏目管理','新添加栏目，对已添加栏目进行修改等操作。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Hclasslist01','栏目管理','整个系统的分类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_logscreat_0001','日历标题','请填写事件的标题，日历提醒的时候将显示此项<br />最大长度为50.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_logscreat_0002','日历日期','事件发生的日期。请正确填写格式。格式为：2007-05-07<br/><font color=red>特别提醒：2007年05月07日也是非法的！</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_logscreat_0003','事件描述','填写的描述。可以为空。最大长度：1000字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_logscreat_0004','提前提醒','如果设置为0，则在当日对用户进行提醒。如填写2，则将在您设定的日期提前2天提醒您！此项必须填写正整数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenulist_0001','删除菜单','如果是系统菜单。则用户或者管理员只能修改名称，其他的不能修改，不能删除！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_001','管理员用户名','管理员的用户名，可以为中文，不能包含“*’”,~”等特殊字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_002','管理员密码','密码长度最大为50个字符。二次密码必须与第一次密码一致。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_003','是否禁用','此项如选是，则您添加的管理员是锁定状态，如选否，则是正常状态。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_004','频道管理员','此项如选是，则添加的是频道管理员，否则不是。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_005','管理员姓名','填写管理员的真实姓名，最大长度为20个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_006','电子邮件','管理员的电子邮件，格式为：admin@foosun.cn！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_007','管理员组','可以为此管理员选择所属的管理员组。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_008','频道超级管理员','可以选择此管理员是否是频道超级管理员，超级频道管理员可以在自已的后台添加自已所属的管理员。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_009','多人登录','如选是，则可以用一个管理员同时登录后台进行操作，否则则不能同时登录。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_010','登陆限制','登录后台的限制，如果不限制则请填0|0，格式为：3|5，说明，3代表错误登录的次数，5代表锁定的时间(单位小时)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_011','IP限制','设置管理员必须在某个IP段才能登录后台系统<br />格式：192.168.1.*，如果有多个IP段用|分割。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminAdd_012','所属频道','为你添加的频道管理员选择所属频道。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminEdit_001','用户名','当前管理员的用户名，不可更改。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminEdit_002','密码','如果不更改密码，则不填写。要更改则请输入你的新密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_GenTitle_0001','常规管理标题','常规管理标题项，此项不允许为空，长度为50-100字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_GenType_0001','常规管理类型','请选择常规类型，有关键字，作者，来源，内部连接，选择相应类型，则显示相应内容框，并进行您的操作。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_GenUrl_0001','常规管理连接地址','此处为常规管理连接地址填写处，请填写有效的连接地址，在生成的页面就可以根据该地址直接转向相应的地址。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_GenEmail_0001','常规管理电子邮件','请填写正确的电子邮件地址，如：koolls@163.com方便与您的联系。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FileManage_0001','文件管理','注意，在您要查看显示的文件列表中，出于安全的因素，您所添加的以.config和.aspx等作为扩展名的文件没有显示出来，若您需要做修改，请直接在您本地机相应硬盘文件夹下执行操作。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0001','统计系统站点名称','统计系统站点名称，长度为0-100个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0002','统计系统站点英文名称','统计系统站点英文名称，长度为0-150个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0003','统计系统IP防刷新','是否开启统计系统IP防刷新功能，默认为不开启，开启了该功能则一个IP只能统计一次，否则同一IP可以多次统计访问。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0005','统计系统在线统计','是否开启统计系统在线统计，默认为开启，开启该功能后，可以统计当前在线访问情况。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0006','统计系统每页记录数','统计系统每页记录数，在显示详细记录的时候，通过您设置的每页统计数，显示相应的条数，一般设为15条，过多会影响效率。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0007','统计系统Cookies','统计系统Cookies时间，长度为0-30个字符，默认为100.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0008','统计系统时间调整','统计系统时间调整，为整数类型，默认为0，表示按北京时间统计数据。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0009','统计系统小数精确度','统计系统小数点的精确位数，一般为3位，位数越多，则统计越精细。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_ChangePass_0001','旧密码','请输入您的旧密码！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_ChangePass_0002','新密码','输入您的新密码。密码长度为3-18位；请尽量使用比较复杂的用户名和密码！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_ChangePass_0003','确认密码','必须和新密码一致！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_sysParamtop0001','系统参数设置','对整个站点系统的参数设置，包括基本属性，会员部分，上传，JS，FTP，RSS，水印，以及第三方开发的API的系统参数设置。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0001','站点名称','<DIV>用于填写前台主页站点名称，如：风讯官方站</DIV><DIV><FONT color=#ff0000>后台程序标题名称请在config文件中配置</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0002','站点域名','此处填写站点主域名，格式如:<FONT color=blue><A href="http://www.foosun.net">www.foosun.net</A></FONT>。系统提示:不允许填写"<FONT color=red>http://" </FONT>以及在后面带"<FONT color=red>/"</FONT>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0003','首页生成的文件名','<DIV>首页生成的文件名，如：index.html。</DIV><DIV><FONT color=#ff0000>如果开启了动态调用，此项不起作用。默认首页文件为defalut.aspx</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0004','默认的扩展名为（主站）','html,shtml,shtm(第一个为：生成栏目扩展名，第2个为：新闻生成的扩展名，第3个为专题生成的扩展名)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0005','后台登陆过期时间','后台管理员登陆过期。单位为秒。必须为正整数。大于600小于6000.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0006','版权信息','前台版权信息：大小限制：1~3000字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0007','搜索关键字长度','0|10.0表示可以填写0个字符，10表示关键最大可以填写字数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0008','生成栏目文件保存路径','<DIV>供选择参数：{@year02} {@year04} {@month} {@day} {@hour} {@minute} {@second} {@Ram<FONT color=#006400>04</FONT>_<FONT color=#ff0000>1</FONT>}(04表示4位随机数字，0表示数字随机，1表示字母随机，2表示字母数字随机) {@自动编号ID} {@ClassId}。</DIV><DIV>示例：{@year02}-{@month}/{@day}-fs-{@自动编号ID}，那么生成的文件名的保存路径就为：06-12/20-fs-12。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0009','生成索引页的规则','<DIV>可定义参数：{@year02} {@year04} {@month} {@day} {@hour}。</DIV><DIV>示范：index_{@year4}/{@month}-{@day}.html，则生成的格式就为：index_2007/2-10.html。</DIV><DIV>此项<FONT color=red>为生成归档使用及门户站新闻栏目终极页面使用</FONT>。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0010','生成新闻的文件命名规则','<DIV>供选择参数：{@year02} {@year04} {@month} {@day} {@hour} {@minute} {@sceond} {@Ram<FONT color=#006400>04</FONT>_<FONT color=#ff0000>1</FONT>}(04表示4位随机数字，0表示数字随机，1表示字母随机，2表示字母数字随机) {@自动编号ID} {@ClassId}。</DIV><DIV>示例：{@year02}-{@month}/{@day}-fs-{@自动编号ID}，那么生成的文件名就为：06-12/20-fs-12。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0011','生成新闻的文件保存路径','供选择参数：{@year02} {@year04} {@month} {@day} {@Ram<FONT color=#006400>04</FONT>_<FONT color=#ff0000>1</FONT>}(04表示4位随机数字，0表示数字随机，1表示字母随机，2表示字母数字随机)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0001','会员注册默认会员组','会员注册的时候默认会员组。会员组可以在会员组管理中进行管理。会员组必须要建立一个默认的。以方便用户注册的时候默认使用。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0002','投稿状态','开启（1）或者关闭（0）。如果不开启投稿状态，前台会员就不会有投稿的连接。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0003','是否允许注册','会员注册开启（1）或者关闭（0）。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0004','注册是否需要验证码','注册是否需要验证码，(1)需要，(0)不需要。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0005','评论是否需要显示验证码','评论是否需要显示验证码，(1)需要，(0)不需要。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0006','是否开启群发功能','会员好友群发功能 ，(1)开启，(0)不开启。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0007','是否允许匿名评论','是否允许匿名评论，(1)开启，(0)不开启。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0008','评论是否需要加载html编辑器','评论是否需要加载html编辑器，(1)开启，(0)不开启。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0009','评论过滤字符','评论过滤字符，用|分开。如：妈的|奶奶的|fuck，法轮功。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0011','会员G币单位','会员G币单位，如风币，金币。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0012','会员注册获得的金币|积分','会员注册获得的金币积分，以|为分割符，格式如：10|5，表示注册后获得金币10，积分获得5。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0013','登陆多少次错误后锁定帐号|锁定','会员登陆多少次错误后锁定帐号|锁定时间。如：3|30表示登陆3次失败后锁定帐号不许再登陆，锁定帐号30分钟(最大2000分钟)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0014','会员注册需知','会员注册需知，此处为会员注册时需要填写的一些注意事项，如：会员注册必须遵守xxx规定，不得危害xxx等等。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0015','会员等级设置','会员等级设置，在这里默认提供10个选项，您可自行设置您需要的一些等级。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0001','图片存放路径是否做为单独域名','图片存放路径是否做为单独域名，若您选择是，则您上传的图片的存放路径将作为一个单独的域名，并填写相应的域名，可以直接访问该域名对里面的图片进行访问。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0002','图片域名','图片域名，如127.0.0.1。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0003','图片（附件）目录','图片(附件)目录，如Picture，则在相应的图片域名下访问时就为：127.0.0.1/Picture。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0004','上传文件允许格式','上传允许的格式。如:jpg,gif,rar,zip(提示:分格使用逗号)');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0005','上传文件允许大小','上传文件允许大小(单位kb)。如:1024，则大于1024kb的上传将被禁止，系统提示：不建议将上传设置过大！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0006','远程图片服务器域名启用','远程图片服务器域名启用，可以在远程域名下，将其作为图片存放域名路径，如：将远程域名222.209.221.121作为我的图片存放路径，则直接可在该域名下访问图片。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0007','远程图片域名','远程图片域名，如220.220.220.220.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0008','远程图片保存路径','远程存图保存路径：格式： /remoteFiles/。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0009','列表每次刷新数','<p>每个栏目最大显示数量（终极栏目列表）：(为0，不限制)。</p>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0011','信息每次刷新最新数','<p>为了减小服务器负荷,选择全部新闻生成，最多生成多少个：(为0，不限制)。</p>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0012','批量删除信息每次删除数','批量删除信息每次删除数：(为0不限制)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UploadParam_0013','专题每次刷新信息数','<p>每个专题终极列表显示的最大数量.(为0不限制)。</p>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_JSParam_0001','是否开启远程发布功能','是否开启远程发布功能，若选择开启，则可以远程直接发布您生成的新闻，更方便快捷。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_JSParam_0002','JS设置','热点新闻设置：可以设置调用多少条新闻，标题字数，点击大于多少最新信息、推荐信息、头条信息、热门评论按照上面来设置。JS模型设置选择参看模型设置。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0001','是否开启水印/缩图功能','是否开启水印/缩图功能，选择开启，则可以对上传的图片加上您需要的水印，或是生成相应大小的缩略图。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0002','水印类型','水印类型，有文字与图片两种，您可以根据自己的需要选择您喜欢的方式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0003','水印文字','水印文字，这里填写您添加上去的水印文字，您可以在这里添加具有您特色的水印文字，如：Foosun，风讯科技制作，<font color="red">注意：该选项只对文字水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0004','水印文字大小','水印文字大小，单位pt，如：12pt，20pt，<font color="red">注意：该项只对文字水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0005','水印字体选择','水印字体选择：默认提供的有宋体，楷体，黑体，隶书四种，<font color="red">注意：该项只对文字水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0006','水印文字颜色','水印文字颜色，点击右边的小图标，选择颜色，<font color="red">注意：该项只对文字水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0007','水印文字是否粗体','水印文字是否粗体，选择文字水印是否为粗体显示，<font color="red">注意，该项只对文字水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0008','水印图片地址','水印图片地址为：如：/files/logo.jpg，<font color="red">注意，该项只对图片水印有效，</font>点击选择按钮进行选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0009','水印图片高、宽','水印图片高、宽，格式为：200|100<font color="red">注意，该项只对图片水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0010','水印图片透明度','水印图片透明度为：填写0.8，表示透明度为80%<font color="red">注意，该项只对图片水印有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0011','水印位置','水印的位置：可选择：居中(0)，左上(1)，左下(2)，右上(3)，右下(4)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0012','是否开启缩图功能','是否开启缩图功能，(1)开启，(0)关闭。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0013','缩图的方式选择','缩图的方式选择，高|宽：格式：100|100，比例：0.5表示50%。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0014','高|宽','高|宽：格式为：100|100.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_WaterParam_0015','比例','比例：0.5。表示50%。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0001','显示最新.范围','显示最新。范围：5-1000。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0002','简介截取数','简介截取数：范围0-3000，如果为0，表示不限制。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0003','RSS标题','此处填写RSS标题，如：风讯Net团队。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0004','RSS图片地址','RSS图片地址，如/rss_files/logo.jpg，点击右边的选择按钮进行选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0005','新闻是否添加到wap服务器中','所有的新闻默认是否添加到wap服务器中，(1)是，(0)否。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0006','wap文件存放路径','wap文件存放路径，默认为：/wap，点击右边按钮选择路径。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0007','Wap捆绑域名','Wap捆绑域名，如http://www.xyz.com。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_rssParam_0008','wap显示最新数','wap显示最新数：范围为：5-500条。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_table_list_0001','表名','<DIV>需要复制的表名。长度为20<BR>表名不能重复。一旦创建后，将不能修改、删除！</DIV><DIV>最多可以创建10个表。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminGroupAdd_001','管理员组名称','管理员组名称，中英文字符不限。不得大于二十个字符(十个汉字)');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminGroupAdd_002','管理的栏目','从左边列表框选择这个管理员组可以管理的栏目。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminGroupAdd_003','管理的频道','从左边列表框选择这个管理员组可以管理的频道。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminGroupAdd_004','管理的专题','从左边列表框选择这个管理员组可管理的专题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_adminGroupEdit_001','管理员组名称','修改时不允许修改名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_0015','管理列表每页显示记录条数','管理列表每页显示记录条数，用来控制管理列表页中每页显示的数量，如我设为10条，那么我在管理页中，如常规管理，列表就每页10条的显示，默认为10条，建议不要设得太大，以免影响效率。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FileManage_0002','文件编辑','注意，只能对.html，。asp，。aspx，。txt，.htm格式的文件进行在线编辑与文本编辑。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('NewsHist01','归档管理','归档管理主要是对归档的新闻进行管理，在这里您可以对归档的新闻进行还原，锁定，生成索引等操作。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surverParam_0001','IP时间间隔','IP时间间隔，就是指同一IP间隔多少时间才能再投票（单位分钟）默认为10。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surverParam_0002','是否需要注册','是否需要注册，就是指是否需要注册成为会员才可以投票，默认为任何人都可以投票，无特殊情况不要选是。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surverClass_0001','类别名称','类别名称，建立您自己想要投票的类别，比如：中超<br><font color=''red''>注意，类别名称不能为空。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surverClass_0002','类别描述','类别描述，就是对您建立的类别的一个总体描述，您建立的类别主要是包括那些方面，指的是什么？比如我建立一类别：中超，其描述可以是：中超我未来如何？');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0001','选择类别','选择您所建立的一些类别信息，在相应的类别下建立其投票主题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0002','调查主题','建立您需要发起投票调查的主题，比如：这顿饭好吃不？');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0003','项目类型','项目类型，在这里选择您所建立的主题是单选，还是多选。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0004','选项个数','本选项只对多选项有效，当您选择主题为多选的时候，选择您多选最多允许选择的个数，如10。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0005','显示方式','选择在前台显示投票结果的显示方式，如柱形图的样式显示，或是以饼图的方式显示，暂只支持柱形图。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0006','开始时间','每个投票主题都有一个时间段，在这里填写上投票的开始时间。点击右边按钮进行时间的选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0007','结束时间','每个投票主题都有一个投票的时间段，在这里填写上投票的结束时间，点击右边的时间选择按钮进行时间的选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0008','显示方式','在前台显示投票结果出来的时候，您可选择下面提供的几种方式，以在前台显示在用户面前，效果更加直观。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0001','所属投票','选择您所建立投票选项的类别和主题，点击下拉列表进行选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0002','选项描述','对您所建立的投票的每一个选项的描述，比如：很好、一般、很差等等。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0003','项目符号','对您所建立的投票的一些选项按照指定的项目符号排列，如：1，很好 2，不好，3很差。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0004','选项模式','选项模式有文字选择模式，自主填写模式，图片模式3种，选择自主填写模式，文字后可以多个录入框，建议选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0005','图片位置','选择一张图片，在前台以图片模式显示，本选择框只对图片模式有效。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0006','显示颜色','选择颜色，控制查看投票时的颜色显示，这样给用户以更加直观的效果。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0007','当前票数','初始当前票数，如我的当前票数为100。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveyitem_0008','选项详细说明','对选项的一个详细介绍，说明。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveysteps_0001','调查主题','选择您需要发起投票调查的主题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveysteps_0002','顺序号','在多步投票中，对您所添加的信息进行步骤排列，如写1就为第一步。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveysteps_0003','调用主题','在某一调查主题下选择在该主题作为调查项时，其调用的一些主题');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_001','专题中文名','专题中文名，不能包含特殊字符，最长五十个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_002','专题英文名','专题英文名，不能包含非法字符，不能重名，最大长度50字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_003','专题父栏目','当前专题的专题父栏目，如果添加的时候没有选择父栏目，则默认为根栏目，修改专题的时候不可更改此项。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_004','专题域名','每个专题可以绑定不同的域名，域名格式为http://www.xxxx.com。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_008','专题文件扩展名','专题文件扩展名：专题被生成静态文件时所使用的文件后缀，可以选择htm html shtm aspx，当选中aspx时可以为专题设置浏览权限。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_005','专题浏览权限','当专题扩展名设置为aspx的时候可以为专题设置浏览权限，如果扩展名设置成了aspx又不需要浏览权限的时候请将会员组置为默认状态。权限可以分为扣取或者必段达到一定的金币以及点数才可以浏览。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_006','专题目录生成规则','专题目录生成规则：年2位，年4位，月，日，时，分，ID自动编号，英文名称，随机数多种组合方式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_007','专题文件生成规则','专题文件生成规则：年2位，年4位，月，日，时，分，ID自动编号，英文名称，随机数多种组合方式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_009','专题保存路径','为你所添加或者修改的专题选择物理的保存路径。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_010','专题导航图片','为你添加或者修改的专题设置在页面上的导航图片。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_011','专题导航文字','为你添加或者修改的专题设置在页面上的导航文字。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_012','专题模板','为你添加或者修改的专题选择与之需要绑定的模板。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_013','专题页面导航','为你添加或者修改的专题设置在页面上的导航条，支持HTML语法。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_014','专题是否锁定','为你添加或者修改的专题选择当前的状态。是为启用此专题。否为不启用此专题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_SpecialAdd_015','专题功能操作帮助','彻底删除：删除专题在数据库中的记录，也删除已生成的静态文件，不可恢复。<br />删除到回收站：将专题放入到回收站，可以在回收站里面恢复。<br />批量解锁：可以给锁定了状态解锁。如果子专题的父专题被锁定，那么此子专题将不能被解锁。<br />批题锁定：可以批量锁定专题，锁定的时候如果被选中的专题有子专题，那么子专题也将被锁定。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_File_Txt_edit_0001','文本编辑','文本编辑，对后缀名为.cs .asp .html .htm .aspx .java .txt等文件的文本方式编辑。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FileTxtEdit_0001','文本编辑','对当前您所打开的文件的一个文本方式的编辑，您可以直接在编辑框里对文件进行更改，然后保存。若您想撤消所做的更改，请点击恢复按钮。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statClass_0001','新增分类','填写您所建立的统计系统分类名称，如新闻类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Recyle_001','指定栏目','有些新闻的父栏目可能还在回收站中，恢复新闻时请指定这一部份新闻应该恢复到那个栏目下面。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchClass_0001','类别查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：类名；那么执行查询操作就可以找出有关键字123，且属于类名这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchTitle_0001','主题查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：主题；那么执行查询操作就可以找出有关键字123，且属于主题这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchItem_0001','选项查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：所属投票；那么执行查询操作就可以找出有关键字123，且属于投票这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchSteps_0001','多步投票查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：调用主题；那么执行查询操作就可以找出有关键字123，且属于调用主题这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surverParam_0003','IP禁止段','设置不能投票的IP段，格式192.168.1.*。如果有多个IP段用|分割。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_001','字段中文名称','文本中不能出现特殊字符，字段长度不能超出50个字符！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_002','字段名(英文名)','此文本框内只出现中英文字符与阿拉伯数字。例：Abc、Abc12、ABC、abc等系列名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_004','是否允许为空','默认为NUll（允许为空）。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_006','字段说明','对这个字段的说明，以便以后的查看。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0009','是否允许多步投票','如果您需要把此主题设置为多步投票，请选择“是”，那么在多步投票建立的时候就会把允许多步投票的主题列选出来，以供选择，若您不需要设置为多步投票。请不要选择此项。默认情况为“不选择”。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FileOnlineEdit_0001','文件在线编辑','对当前您所打开的文件的一个在线方式的编辑，您可以直接在编辑框里对文件进行更改，然后保存。若您想撤消所做的更改，请点击恢复按钮。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0003','城市','请填写你所在的城市。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FileTxtEdit_0001','文本编辑','对当前您所打开的文件的一个文本方式的编辑，您可以直接在编辑框里对文件进行更改，然后保存。若您想撤消所做的更改，请点击恢复按钮。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statClass_0001','新增分类','填写您所建立的统计系统分类名称，如新闻类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Recyle_001','指定栏目','有些新闻的父栏目可能还在回收站中，恢复新闻时请指定这一部份新闻应该恢复到那个栏目下面。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchClass_0001','类别查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：类名；那么执行查询操作就可以找出有关键字123，且属于类名这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchTitle_0001','主题查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：主题；那么执行查询操作就可以找出有关键字123，且属于主题这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchItem_0001','选项查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：所属投票；那么执行查询操作就可以找出有关键字123，且属于投票这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchSteps_0001','多步投票查询','此查询操作，您需要在关键字处输入您要查找的内容名，并在旁边选择查询的类型，如关键字：123 查询类型：调用主题；那么执行查询操作就可以找出有关键字123，且属于调用主题这个类别的字段内容，查询操作支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surverParam_0003','IP禁止段','设置不能投票的IP段，格式192.168.1.*，如果有多个IP段用|分割。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_002','字段名(英文名)','此文本框内只出现中英文字符与阿拉伯数字。例：Abc、Abc12、ABC、abc等系列名称');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_003','字段类型','<DIV><FONT color=#ff0000>文本框：</FONT>普通的文本输入类型</DIV><DIV><FONT color=#ff0000>下拉列表：</FONT>下拉列表类型</DIV><DIV><FONT color=#ff0000>选择本地文件：</FONT>选择计算机本地上的文件</DIV><DIV><FONT color=#ff0000>选择图片：</FONT>选择服务器上系统指定目录的图片</DIV><DIV><FONT color=#ff0000>选择文件：</FONT>选择服务器上系统指定目录的文件</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_004','是否允许为空','默认为NUll（允许为空）');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_005','字段默认值','<DIV><FONT color=#ff0000>下拉列表\单选\复选</FONT>：每一个项目用回车分开</DIV><DIV><FONT color=#ff0000>文本框\其他类型</FONT>：直接输入默认值，不要回车</DIV><DIV>&nbsp;</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_006','字段说明','Def_Table_006');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_surveytitle_0009','是否允许多步投票','如果您需要把此主题设置为多步投票，请选择“是”，那么在多步投票建立的时候就会把允许多步投票的主题列选出来，以供选择，若您不需要设置为多步投票。请不要选择此项。默认情况为“不选择”。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FileOnlineEdit_0001','文件在线编辑','对当前您所打开的文件的一个在线方式的编辑，您可以直接在编辑框里对文件进行更改，然后保存。若您想撤消所做的更改，请点击恢复按钮。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendParam_0001','是否开放友情连接申请','默认为选中状态，表示开放友情连接申请，若您想取消该此选中状态，将是不开放连接申请。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendParam_0002','注册会员才能申请','此项表示友情连接必须是注册后的会员才可以申请此连接，否则不是会员就不能申请。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendParam_0003','友情连接图片最大及最小尺寸','若为图片友情连接，该项就对其图片的大小进行控制，格式为80，30，以逗号分隔。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendParam_0004','申请连接须知','此项填写在申请友情连接的时候需要注意的一些事项，如：必须遵守xx规则，不得xx样等等，支持html格式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendParam_0005','申请的连接是否要审核','若选择此复选框，则表示申请连接需要审核，通过后才可以使用，否则无效。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendClass_0001','分类名称','填写您所添加的分类名称，长度为1-50个字符。如：风讯文字类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendClass_0002','英文名称','填写您所添加的分类的英文名称，长度为1-50个字符。如：foosunClass。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendClass_0003','分类说明','填写您所添加的分类的详细说明。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0001','选择类别','选择您在添加连接的时候相应连接所属的类别，以便进行分类管理。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0002','站点名称','填写您添加友情连接时的站点连接名称。如风讯科技。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0003','连接类型','选择您添加连接时的连接类型，类型有文字与图片两种类型，默认为文字连接类型。根据需要选择您所喜欢的连接方式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0004','连接地址','连接地址就是指您在添加相应连接时的转向连接地址，如：我添加一个文字连接，其连接地址为：htp：//www.foosun.net。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0005','站点说明','站点说明就是指对您添加的连接站点的一个简要介绍，大致说明。如：我的文字连接为：风讯科技，其说明可以是：网站建设，程序开发等等。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0006','图片地址','若您选择的是图片连接，则在该处选择添加时的图片连接地址。<br><font color=''red''>注意：该项只对图片连接有效。</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0007','是否锁定','该项表示对您所添加的连接是否锁定，选择是则前台不能调用，请谨慎使用。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0008','高级选项','选中此复选框，可以对您所添加的连接进行一些高级设置，使您的连接信息更加精确。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0009','前台会员申请','若选择是，则您所您所添加的连接信息为前台会员申请的连接。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0010','申请人作者','为添加该连接的作者或是添加人的编号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0011','申请人邮件','添加该连接的作者的邮件地址。如：kooll2@163。com');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0012','申请理由','申请添加该连接的理由，您为什么申请该连接。在这里填写理由。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0013','其他联系方式','申请连接作者的一些联系方式，请尽量填写详细，以便与您联系。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_FriendLink_0014','申请时间','该时间为您在添加连接时选择时间，不能修改。请点击按钮进行选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0001','选择类别','选择申请的友情连接的类别，以便可以分类添加您需要的连接类型。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0002','站点名称','填写您申请的友情连接的站点名称。如：风讯科技。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0003','连接类型','提供文字连接与图片连接两种。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0004','连接地址','填写您添加的友情连接的连接地址，如http://www.foosun.net');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0006','申请人编号','继承您的会员编号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0007','申请人邮件','继承您的电子邮件。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UFriendLink_0020','查看申请','点击复选框，查看申请协议。取消则隐藏。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_searchlink_0001','连接查询','在关键字处填写查询关键字，并选择查询类型，根据类型查询您需要的信息，其中会员（锁定）：表示由会员添加的连接且为锁定的项，同理，其他一样。支持模糊查询。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_friendClass_001','父类编号','父类编号，若不是父类，则默认为0，否则为其父类的编号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0005','统计系统在线统计','开启统计系统的在线统计功能，即可对在线访问情况进行统计，默认为开启状态。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_01','栏目中文名称','栏目中文名，不能包含特殊字符，长度为2-50个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_02','栏目英文名称','栏目英文名，不能包含非法字符，不能重名，最大长度50字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_03','父栏目编号','当前栏目的父栏目，如果添加的时候没有选择父栏目，则默认为根栏目。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_04','是否外部栏目','选择此栏目是否为外部栏目。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_05','权重','<DIV>输入栏目的权重大小，范围：0-10.</DIV><DIV><FONT color=#ff4500>数字越大，越靠前</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_06','外部栏目地址','输入外部栏目地址，如：http://www.xxxx.com');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_08','捆绑域名','每个栏目可以绑定不同的域名，域名格式为<A href="http://www.xxxx.com">http://www.xxxx.com</A>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_09','栏目模板','选择栏目页所绑定的模版。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_10','栏目内容页模板','选择属于该栏目下面的新闻所绑定的模版，也就是添加新闻时，新闻页面默认继承的新闻模板。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_001','广告名称','广告名称，长度不能超过25字。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_002','广告所属分类','为你所添加的广告选择分类，如果当前没有分类，请添加广告类别再添加广告。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_003','广告类型','请选择你添加的广告是属于那种类型。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_004','左图(动画)地址','为你所添加的广告选择左图(动画)的地址。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_005','左图(动画)宽高','为你所添加的广告填写宽高，格式为200|200.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_006','右图(动画)地址','为你添加的广告填写右图(动画)地址。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_007','右图(动画)宽高','为你添加的广告填写右图(动画)宽高，格式200|200.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_008','链接地址','为你添加的广告填写链接地址，格式为http://www.foosun.net');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_009','循环广告位','为当前的循环广告选择与那个广告一起循环。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_010','循环速度','为你添加的循环广告填写循环速度。只能为正整数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_011','循环方向','为你添加的循环广告选择循环方向。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_013','文字广告','需填写文本内容，链接地址。以及填写显示的列数，只能为正整数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_012','显示条件','选择此广告是否有显示的条件，基中包括最大显示数，到期时间，点击次数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_014','最大显示数','此广告的最大显示数，如果到达此设置的数字，则此广告将失效。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_015','到期时间','为此广告设置到期的时间，如果到达此时间，则此广告将失效。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_016','最大点击次数','为此广告设置最大的点击次数。如果到达设定的数字，则此广告将失效。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_017','是否锁定','是否锁定此广告，如果是锁定状态。那么此广告不能被使用。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_018','分类名称','为你添加的栏目填写名称，不超过25字。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_019','父类编号','如果是顶级栏目，则父类编号为0。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_AdsAdd_020','分类价格','主要用于会员可以申请此栏目下面的广告需要扣除多少个金币。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_announce_add_0003','权限设置','示例：0|2|1<br />第一个参数需要积分；第二个参数表示需要G币；第三个参数表示需要魅力值。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0001','稿件名称','所投稿件名称不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0003','作者','如果不添作者，则稿件作者为登录的会员。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0005','频道分类','选择稿件所投频道。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0006','稿件分类','选择自己建立的投稿分类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0008','类 型','选择所投稿件的来源。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0011','图片','如果所投稿件有图片要选择稿件中的图片。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0001','真实姓名','填写自己的真实姓名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0002','开户银行','填写要收取稿费的开户银行。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0003','开户名','填写自己开户银行的开户名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0004','银行账号','填写自己的开户银行。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0005','卡号','填写开户银行的卡号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0006','地址','填写地址。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constraccount_add_0007','邮政编码','填写邮政编码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_ConstrClass_up_0001','分类名称','分类名称不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_ConstrClass_up_0002','分类描述','填写分类描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statClass_001','父类编号','父类编号，根类为0，其余的子类继承父类的编号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_11','栏目保存路径','指当设置为生成静态文件时，此栏目页面的保存路径。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_12','是否导航中显示','选择是否在导航中显示该栏目。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_13','栏目审核机制','设置栏目的审核机制，默认为不审核。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_14','新闻保存规则','指当选择生成静态文件时，此栏目下新闻生成的静态页保存路径。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_15','使用新闻数据表','选择保存该栏目下新闻所使用的数据表，默认为：FS_News。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_16','多少天后归档','<DIV>默认为180天。</DIV><DIV>如果不需要归档，请设置为0.</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_17','频道编号','频道编号，系统自动产生的ID。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_18','自定义自段','选择该栏目新增加的自定义字段。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_19','目录结构','设置栏目生成目录结构规则。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_20','文件命名规则','<DIV>设置栏目文件名命名规则。</DIV><DIV>后面必须带文件名。</DIV><DIV><FONT color=#ff0000>格式：china/index.html 或china/china.html</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_21','索引页规则','');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_22','浏览文件命名规则','设置新闻浏览文件命名规则。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_23','图片上传目录','该栏目上传图片的保存目录。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_24','浏览权限','设置浏览该栏目的权限。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_25','生成文件扩展名','生成栏目文件的扩展名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_27','栏目导航说明','为你添加或者修改的栏目设置在页面上的导航文字。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_30','Meta关键字','添加该栏目的Meta关键字。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_31','Meta描述','添加该栏目的Meta描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_32','用户发表言论','选择用户是否可以对该栏目下的新闻进行评论。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_33','新闻页面导航','新闻内容页在位置导航中的显示样式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_psf_0001','接点名称','接点名称，不能重复，必须填写。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_psf_0002','设置个数','设置您在远程发布时需要上传的一些目录个数，比如我需要把我本地的news，down，mall三个目录下的文件上传到远程指定的文件目录下面，那么此时就需要您设置3个目录间的对应关系。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_psf_0003','上传子目录下的文件','选择此项后表示在上传的过程中，会自动把相应目录下的子目录及文件一起上传到远程目录去。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_psf_0006','接点目录关系','在本地目录填写本地您需要上传的文件夹，在远程目录下填写您上传的远程目录，如本地wwwroot/news，远程psf/news就表示把本地相应news下的文件上传到远程psf/news下去。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_psf_0005','选择时间','本地时间，不能修改。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0001','任务名称','填写您发布站点的任务名称，不能为空。长度为3-50个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0002','生成首页','此项必须选择，在发布站点时将发布新闻首页，若不选，将出现异常情况。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0012','定时发布','选择您做为定时发布的时间点，如您选择2，就表示2点时自动发布任务。可以多选。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0003','创建时间','本地时间。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0004','生成所有栏目的索引页','选择此项，表示在发布生成的时候生成所有栏目的一个索引页，否则不生成。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0005','按照每天一页的方式生成所有栏目','按照每天一页的方式生成所有栏目的索引，此项表示将栏目按照每天一个索引的方式生成索引页，如一个月30天的话，那么在生成就会每天生成一个索引页。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0006','只生成今天的栏目索引','只生成今天的栏目索引，表示在生成的时候只生成今天时间的索引页，其他时间段不生成。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0007','按照栏目发布','选择您需要发布的栏目，按住Ctrl键进行多选，按住Ctrl键再次点击已选中的栏目表示取消。也可按住左键拉动鼠标进行选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0008','生成所有新闻','此项表示发布生成所有的新闻。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0009','新闻ID','此项表示您可以按照新闻ID的一个范围，在这个范围之间进行生成发布。<br><font color=''red''>注意：必须两个ID都填写，否则将默认为0，表示不按照ID发布</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0010','新闻日期','此项表示您可以按照日期的一个范围，在这个范围之间进行生成发布。<br><font color=''red''>注意：必须两个日期都填写，否则将默认为0，表示不按照日期发布</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_0011','新闻数量','此项表示您可以根据您添加的最新新闻数进行生成，比如我最新添加了20条新闻，若我填10，就表示生成当前最新添加的10条新闻。<br><font color=''red''>注意：若不填写，保留为空或是不正确格式的值，将出错或是默认为0，表示不按照该条件发布</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_task_00013','新闻专题','选择您需要发布的专题，按照专题ID进行发布生成。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0020','冲值类型','冲值类型，0表示冲值为积分，1表示冲值为G币　默认为1');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('y_newsadd_01','新闻标题','新闻长度不能超过80个字符串。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_changeSkin_001','更改皮肤','请填写皮肤名称。可以选择填写的目录有。<br />blue(兰色皮肤，默认的皮肤)<br />red(橘红色皮肤)<br />green(绿色皮肤)<br />blackwhite(黑白皮肤)<br />用户自定义皮肤：如果用户需要自定义皮肤。把皮肤按照目录存放到sysImages/目录下。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_registerParam_0003','邮件验证','用户注册成功后，需要到邮箱里取回密码！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_registerParam_0004','手机认证','用户注册必须填写手机，并输入验证信息才能进行下一步注册！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_statParam0004','IP防刷新时间','统计系统IP防刷新时间，表示在该时间内不允许统计数据信息。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0010','会员IP登陆限制','设置会员不能在某个IP段登录会员前台<br />格式：192.168.1.*。如果有多个IP段用|分割。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_psf_0007','上传文件目录下最新内容','上传文件目录下最新内容，选中此复选框，表示在上传的时候只上传该文件目录下的最新的内容，否则上传的内容为该文件目录下的所有文件。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0017','魅力值增加','格式：1|1，第一个值表示登陆一次魅力值加1，第二个值表示发表评论，投票，讨论组，投稿一次，魅力值加1，如我填写5|10，就表示登陆一次魅力值加5，第二个值表示发表评论，投票，讨论组，投稿一次，魅力值加10');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_0018','活跃值增加','格式：1|1，第一个值表示登陆一次活跃值加1，第二个值表示发表评论，投票，讨论组，投稿一次，活跃值加1，如我填写5|10，就表示登陆一次活跃值加5，第二个值表示发表评论，投票，讨论组，投稿一次，活跃值加10');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsclass_0001','JS分类名称','填写JS分类的名称，不能为空，长度为3-50个字符。如：分类一、分类二等等。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0001','选择类别','选择您所添加的JS所属的分类，可以方便的按照类别进行分类管理。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0002','JS名称','填写JS建立的名称，不能为空，必须填写。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0003','JS类型','选择您所要建立的JS的类型，提供自由JS与系统JS两种类型。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0006','新闻调用数量','该JS调用新闻的数量，默认为10条新闻数据。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0007','每行显示数','必须为数字，默认为1，表示一行一条数据的显示。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0008','标题字数','默认为10个长度的字数，根据自己的需要设定其长度数量。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0009','内容字数','默认为200字，可以根据自己的新闻数量设定，一般建议不要设定太多，否则影响页面的视觉效果。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0010','导航字数','默认为5个长度的字数，建议不要太多的字数');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0011','JS模型','选择对您所添加的JS的模型，并继承模型中的一些字段属性。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0004','JS文件名','必须填写，不能为空，表示您添加的JS保存在计算机上的文件名，不需要加.js扩展名。如foosun');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0005','JS文件保存路径','对您建立的JS保存的路径，点击路径选择按钮进行选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0012','创建时间','本地时间，一般不需要做更改。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsadd_0013','JS描述','对您建立的JS的一个简要的描述或是说明。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsmclass_0001','分类描述','对您所建立的模型的详细描述或是说明。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jsmclass_0002','创建日期','当前时间即为添加分类的时间，一般不做更改。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jstemplet_0001','模型名称','填写您所添加的模型名称，不能为空，长度为3-50个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jstemplet_0002','模型分类','选择分类，可以对您所添加的模型进行分类管理。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_registerParam_0001','注册参数','该框内数据为会员注册时所填的一些数据项，根据需要您可以设置在注册时需要的填写项。<br><font color="red">不能为空！</font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_registerParam_0002','选择参数','点击复选框，选择需要在注册时显示的参数。再次点击即取消选择。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jstemplet_0005','创建调用格式','点击“创建调用格式”，在列表标签里选择您创建的系统JS模型所需要的一些参数设置。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_jstemplet_0004','插入通用标签','选择您需要的标签样式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('u_friend_add_0001','添加好友','好友名不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_tags','什么是标签','<STRONG>什么是标签</STRONG><BR>文章标签是一种由您自己定义的，比分类更准确、更具体，可以概括文章主要内容的关键词。 <BR>通过给文章定制标签，文章作者可以让更多人更方便准确的找到自己的文章；而读者可以通过文章标签更快找到自己感兴趣的文章。 <BR>您可以为每篇文章添加一个或多个标签，发表成功后，您可以打开文章内的标签，看到站内所有和您使用了相同标签的文章。<BR>不仅如此，如果您文章内使用的某个标签恰巧在首页上推荐，用户打开这个标签时，就会在结果页面上看到您的文章。 <BR><STRONG>如何使用标签：</STRONG><BR>·标签之间使用"|"间隔； ·每篇文章最多可以使用50个汉字(100个字符)作为文章标签； <BR>·标签过长可能会影响页面美观，建议您尽量使用短一些的词组作为文章标签； <BR>·请不要使用违法内容作为标签，不支持特殊字符和纯数字组合； <BR><BR><STRONG>使用标签的好处：</STRONG><BR>·令文章增加被访问的机会：添加标签的文章会被搜索引擎所记录，其他用户查找相关标签时，会准确查找到使用这个标签的文章。<BR>·拓展视野，找到更多朋友：通过标签您可以找到使用相同标签的文章，并找到文章的作者，这样不仅延伸您的视野，还可以找到志同道合的朋友。<BR>·更自由、准确的管理自己的文章：添加标签的内容完全由您自己决定，不用再将文章放到不对应的系统分类中，也不用再因为兴趣广泛而建立大量的文章分类。标签完全根据您的需要添加，更自由更准确管理文章。 ');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_VoteContent','内容投票','多行请使用回车。一行表示一个投票项目。<br /><font color="red">格式：投票项目|投票数。</font><br />"|"前面表示数量项目投票项目，"|"后面表示投票数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_Manage_001','修改新闻属性','如果不选择此项，则不填写的地方默认不修改');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0006','设置点卡的过期日期','如果不填写。则过期日期为：2099-01-01 00:00:00；<br />窄意理解为永不过期。正确填写格式为：2007-5-18');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_0001','输入生成数量','生成数量范围1-999。<br />请填写正整数');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_levels','会员等级','请按照积分顺序填写。第一行为最低积分，依次递增到最后一行。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_Discount','折扣率','该会员组会员在本站购买商品、点卡的折扣率。<BR>范围为：0-1； <BR>实例：如果：0.9表示9折，0.5表示5折，1表示无折扣');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_downfiles','采集文件到本地','可以采集的东西支持任意文件格式。<br />如果您选择了此项。在内容中包括以下文件名的文件将被下载到本地<br />"gif"， "jpg"， "bmp"， "png"， "jpeg"，"ico"， "swf"， "rar"， "zip"， "cab"， "doc"， "rm"， "ram"， "wav"， "mid"， "mp3"， "avi"， "wmv"');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_bMobile_002','验证码','请填写您手机收到的认证码。<br />您将在几分钟内收到验证码。请不要刷新此页面。<br />如果在几分钟内没收到信息，请重新捆绑！');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00034','用户标志','可以选择颜色，粗体等；如：左HTML|右HTML。<br />实例：<font color=red><b>(高级用户)|</b></font>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_Pass','密码保护','是否开启密码保护<br />第1位：如果为1，表示开启密码保护。<br />    第2位：表示是否在安全码中加随机码<br />    第3位：0表示随机码加在安全码前面，1为加在后面<br />');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_subtitleContent','子新闻','<DIV><FONT color=#c71585>设置格式为&nbsp;</FONT></DIV><DIV><FONT color=#c71585>内容标题$内容的12位编号$粗体，斜体，颜色$新闻表$列数；一行一条内容，多条请用回车</FONT></DIV><DIV><FONT color=#c71585>如果不知道参数，请不要轻易修改新闻12位编号，新闻表，否则很容易出错。</FONT></DIV><DIV><FONT color=#c71585>在添加的时候，不要在字符串中出现多余的"$"标志。</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_label_out_002','导出标签','<DIV>把标签导出下载到本地。</DIV><DIV>生成格式为。xml</DIV><DIV>如果选择备份标签到服务器。那么标签将存放到服务器/xml/label目录下！</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_label_in_tb','导入标签说明','如果您在选择的导入XML文件里，如果有系统内置标签，那么此项选择栏目，不管选择与否。系统将自动把标签归类为系统标签，并存放到设定的系统标签目录里。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_label_in_sfiles','选择标签文件','<DIV>必须选择按照风讯定义的规则的xml。</DIV><DIV>示范：</DIV><DIV><FONT color=#ffa500>&lt；?xml version="1。0" encoding="utf-8"?&gt；</FONT></DIV><DIV><FONT color=#ffa500>&lt；rss version="2。0"&gt；</FONT></DIV><DIV><FONT color=#ff0000>&lt；foosunlabel&gt；</FONT></DIV><DIV>&nbsp; <FONT color=#0000cd>&lt；labelitem&gt；</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelname&gt；新闻浏览&lt；/labelname&gt； <FONT color=#006400>///标签名称</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelid&gt；084160273572&lt；/labelid&gt；<FONT color=#006400>///标签的ID</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelclassid&gt；906201990282&lt；/labelclassid&gt；<FONT color=#006400>///标签的栏目(导入无用，只是为了方便识别)</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelcontent&gt；{FS：API=0，。。。}&lt；/labelcontent&gt；<FONT color=#006400>///标签内容</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labeldescription&gt；描述&lt；/labeldescription&gt；<FONT color=#006400>///描述</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelcreattime&gt；2007-7-14 17：45：32&lt；/labelcreattime&gt；<FONT color=#006400>///创建时间</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelissys&gt；0&lt；/labelissys&gt；<FONT color=#006400>///系统标签，1为是，0为否</FONT></DIV><DIV>&nbsp; <FONT color=#0000cd>&lt；/labelitem&gt；</FONT></DIV><DIV><FONT color=#ff0000>&nbsp;&lt；/foosunlabel&gt；</FONT></DIV><DIV><FONT color=#ffa500>&lt；/rss&gt；</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_label_in_001','导入标签','<DIV>必须选择按照风讯定义的规则的xml。</DIV><DIV>请选择本地xml文件！</DIV><DIV>示范：</DIV><DIV><FONT color=#ffa500>&lt；?xml version="1。0" encoding="utf-8"?&gt；</FONT></DIV><DIV><FONT color=#ffa500>&lt；rss version="2。0"&gt；</FONT></DIV><DIV><FONT color=#ff0000>&lt；foosunlabel&gt；</FONT></DIV><DIV>&nbsp; <FONT color=#0000cd>&lt；labelitem&gt；</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelname&gt；新闻浏览&lt；/labelname&gt； <FONT color=#006400>///标签名称</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelid&gt；084160273572&lt；/labelid&gt；<FONT color=#006400>///标签的ID</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelclassid&gt；906201990282&lt；/labelclassid&gt；<FONT color=#006400>///标签的栏目(导入无用，只是为了方便识别)</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelcontent&gt；{FS：API=0，。。。}&lt；/labelcontent&gt；<FONT color=#006400>///标签内容</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labeldescription&gt；描述&lt；/labeldescription&gt；<FONT color=#006400>///描述</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelcreattime&gt；2007-7-14 17：45：32&lt；/labelcreattime&gt；<FONT color=#006400>///创建时间</FONT></DIV><DIV>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt；labelissys&gt；0&lt；/labelissys&gt；<FONT color=#006400>///系统标签，1为是，0为否</FONT></DIV><DIV>&nbsp; <FONT color=#0000cd>&lt；/labelitem&gt；</FONT></DIV><DIV><FONT color=#ff0000>&nbsp;&lt；/foosunlabel&gt；</FONT></DIV><DIV><FONT color=#ffa500>&lt；/rss&gt；</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_pop_ext','扩展权限','<DIV>本扩展提供强大的权限扩展功能</DIV><DIV>您只需要修改：/xml/sys/pop/API/index。xml 配置文件。</DIV><DIV>添加您需要的权限</DIV><DIV>您可以手动添加，也可以通过程序自动创建</DIV><DIV>/xml/sys/pop/API/index。xml 创建说明：</DIV><DIV class=c><SPAN class=m><FONT color=#0000ff><STRONG><FONT color=#ff0000>&nbsp;</FONT></STRONG>&lt;</FONT></SPAN><SPAN class=t><FONT color=#990000>item</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV><DIV class=e><DIV><SPAN class=b><STRONG><FONT color=#ff0000>&nbsp;</FONT></STRONG></SPAN>&nbsp;&nbsp;&nbsp; <SPAN class=m><FONT color=#0000ff>&lt;</FONT></SPAN><SPAN class=t><FONT color=#990000>popname</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN><SPAN class=tx><STRONG>扩展权限的名称</STRONG></SPAN><SPAN class=m><FONT color=#0000ff>&lt;/</FONT></SPAN><SPAN class=t><FONT color=#990000>popname</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV></DIV><DIV class=e><DIV><SPAN class=b><STRONG><FONT color=#ff0000>&nbsp;</FONT></STRONG></SPAN>&nbsp;&nbsp;&nbsp; <SPAN class=m><FONT color=#0000ff>&lt;</FONT></SPAN><SPAN class=t><FONT color=#990000>popnumber</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN><SPAN class=tx><STRONG>扩展权限的权限代码</STRONG></SPAN><SPAN class=m><FONT color=#0000ff>&lt;/</FONT></SPAN><SPAN class=t><FONT color=#990000>popnumber</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN> </DIV></DIV><DIV><SPAN class=m><FONT color=#0000ff>&lt;/</FONT></SPAN><SPAN class=t><FONT color=#990000>item</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV><DIV><SPAN class=m><FONT color=#0000ff>说明：</FONT></SPAN></DIV><DIV><SPAN class=m><FONT color=#0000ff>&nbsp;<SPAN class=t><FONT color=#990000><FONT color=#1e90ff>popname</FONT>节点：权限的具体代码。可以使用html语法</FONT></SPAN></FONT></SPAN></DIV><DIV><SPAN class=m><FONT color=#990000><SPAN class=t><SPAN class=t><FONT color=#990000><FONT color=#1e90ff>&nbsp;popnumber</FONT>节点：权限的具体代码。您必须使用A开始。4个字符。</FONT></SPAN></SPAN></FONT></SPAN><SPAN class=m><FONT color=#990000><SPAN class=t><SPAN class=t>如：A050，不能使用html语法</SPAN></SPAN></FONT></SPAN></DIV><DIV><SPAN class=m><FONT color=#990000><SPAN class=t><SPAN class=t>多个权限请创建多个节点&lt;item&gt;&lt;/item&gt;</SPAN></SPAN></FONT></SPAN></DIV><DIV><SPAN class=m><FONT color=#990000><SPAN class=t><SPAN class=t></SPAN></SPAN></FONT></SPAN>&nbsp;</DIV><DIV><SPAN class=m><FONT color=#990000><SPAN class=t><SPAN class=t>示例：</SPAN></SPAN></FONT></SPAN></DIV><SPAN class=m><FONT color=#990000><SPAN class=t><SPAN class=t><DIV class=e><SPAN class=b><STRONG><FONT face="Courier New" color=#ff0000>&nbsp;</FONT></STRONG></SPAN> <FONT color=#0000ff><SPAN class=m>&lt;?</SPAN><SPAN class=pi>xml version="1。0" encoding="utf-8" </SPAN><SPAN class=m>?&gt;</SPAN></FONT> </DIV><DIV class=c><SPAN class=m><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp; &lt;</FONT></SPAN><SPAN class=t>rss</SPAN><SPAN class=t> version</SPAN><SPAN class=m><FONT color=#0000ff>="</FONT></SPAN><B>2。0</B><FONT color=#0000ff><SPAN class=m>"</SPAN><SPAN class=m>&gt;</SPAN></FONT></DIV><DIV class=e><DIV class=c><SPAN class=m><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp; &lt;</FONT></SPAN><SPAN class=t>foosunpop</SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV><DIV><SPAN class=m><FONT color=#0000ff><DIV class=c><SPAN class=m><FONT color=#0000ff><STRONG><FONT color=#ff0000>&nbsp;</FONT></STRONG>&lt;</FONT></SPAN><SPAN class=t><FONT color=#990000>item</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV><DIV class=e><DIV><SPAN class=b><STRONG><FONT color=#ff0000>&nbsp;</FONT></STRONG></SPAN>&nbsp;&nbsp;&nbsp; <SPAN class=m><FONT color=#0000ff>&lt;</FONT></SPAN><SPAN class=t><FONT color=#990000>popname</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN><SPAN class=tx><STRONG>广告管理</STRONG></SPAN><SPAN class=m><FONT color=#0000ff>&lt;/</FONT></SPAN><SPAN class=t><FONT color=#990000>popname</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV></DIV><DIV class=e><DIV><SPAN class=b><STRONG><FONT color=#ff0000>&nbsp;</FONT></STRONG></SPAN>&nbsp;&nbsp;&nbsp; <SPAN class=m><FONT color=#0000ff>&lt;</FONT></SPAN><SPAN class=t><FONT color=#990000>popnumber</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN><SPAN class=tx><FONT color=#990000>A050</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&lt;/</FONT></SPAN><SPAN class=t><FONT color=#990000>popnumber</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN> </DIV></DIV><DIV class=c><SPAN class=m><FONT color=#0000ff>&lt;/</FONT></SPAN><SPAN class=t><FONT color=#990000>item</FONT></SPAN><SPAN class=m><FONT color=#0000ff>&gt;</FONT></SPAN></DIV><DIV class=c><SPAN class=m>&lt;/foosunpop&gt;</SPAN></DIV><DIV class=c><SPAN class=m>&lt;/rss&gt;</SPAN></DIV></FONT></SPAN></DIV></DIV></SPAN></SPAN></FONT></SPAN>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('adminHelp','管理员上路帮助','<OL><LI>设置您的参数:控制面板--&gt;参数设置</LI><LI><DIV>创建栏目(可以先创建频道,默认频道为新闻频道)</DIV></LI><LI><DIV>创建标签引用样式</DIV></LI><LI><DIV>创建模板</DIV></LI><LI><DIV>插入标签</DIV></LI><LI><DIV>添加新闻</DIV></LI><LI><DIV>发布页面(动态调用无须发布页面)</DIV></LI></OL>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_labelclassadd_001','指标签的分类名称','分类名称(标签分类名称)：创建标签分类主要是便于众多标签的管理');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_sNewsTitle','新闻副标题','添加新闻的副标题，可以为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_006','选择栏目','<DIV>选择新闻所属栏目，必选项。</DIV><DIV>特别注意：</DIV><DIV><FONT color=#ff0000><STRONG><U>如果您选择的栏目有自定义字段，将不能更改栏目！</U></STRONG></FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_004','权重选择','按权重排序时，权重越大越靠前。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_007','选择专题','选择新闻所属专题，可以为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_Templet','新闻模版地址','选择新闻绑定的模版，不能为空。如不修改，则默认继承所属栏目绑定的新闻模版。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_PicURL','图片地址','图片连接地址，选择本地图片。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_URLaddress','外部地址','所指向的网站地址，如：http://www.sina.com。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_FileEXName','审核新闻','<DIV>是否审核所添加的新闻。</DIV><DIV><FONT color=#ff0000>如果此新闻存在多级审核权限，则不能修改！</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_SavePath','新闻保存路径','选择保存新闻的路径格式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_FileName','新闻文件名称','选择保存新闻的文件名格式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_VoteTF','新闻投票','是否允许为该新闻投票。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_ContentPicTF','画中画','<DIV>开始画中画广告。</DIV><DIV><BR>可以插入HTML语法,如果设置不是图片或者FLASH,则画中画广告,宽度和高度无效.<BR>支持google、baidu等联盟广告。插入html或js代码既可。最大长度不能大于200个字符。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_ContentPicURL','画中画广告','<DIV>画中画广告图片或者FLASH地址或html语法。</DIV><DIV>可以插入HTML语法,如果设置不是图片或者FLASH,则画中画广告,宽度和高度无效.</DIV><DIV>支持google、baidu等联盟广告。插入html或js代码既可。最大长度不能大于200个字符。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_labelclassadd_002','分类名称描述','分类名称描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_ContentPicSize','画中画图片大小','设置画中画的图片大小。单位为"象素"。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0001','昵称','请填写您对外的昵称，可以为中文 。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00030','真实姓名','请填写您的真实姓名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_group','会员组','请选择您所属的会员组。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0002','性别','请选择您的性别。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0003','出生日期','请选择您真实的出生日期，该项用于取回密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0004','民族','请填写您所属的民族。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0005','籍贯','请填写您所属的籍贯。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0006','签名','添加会员的个人签名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0007','会员头像','请选择您的个人头像，用(100|100)这样的格式设置头像大小，最大为120xp。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Labeladd_001','标签分类选择','创建标签时，选择此标签的所属标签分类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0008','性格','请填写您的性格。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0009','爱好','请填写你的个人爱好。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Labeladd_003','标签描述','标签描述：指对此标签的说明。以便以后查看方便。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0010','关系','请填写你的组织关系，如：团员。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0011','职业','请填写你现在所从事的职业。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0012','学历','请填写你现在的学历。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0013','毕业院校','请填写你的毕业院校。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_styleadd_001','选择样式分类','指创建的样式时，选择样式保存在哪个样式分类里面，便于管理样式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_styleadd_002','插入内容','<DIV>指创建样式时，插入的相关字段，包括新闻字段，栏目字段，专题字段，自定义字段。</DIV><DIV>例如：标题，新闻内容，作者，来源。。。。。。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_28','栏目导航图片','为你添加或者修改的栏目设置在页面上的导航图片。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_0014','婚否','请选择你是否已经结婚。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_manage_00015','对外开放','请你选择是否对外开放联系方式。不开放外人将不可以看见你的联系信息。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_page_add_Templet','单页面模版','设置单页面绑定模版，不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_styleadd_003','样式描述','指对此样式的一些说明。便于以后查看管理。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_EName','频道英文命名规则','系统自动取频道中文名称每个字的第一个字母命名。也可以自己手动命名，不能包含非法字符，不能重名，最大长度50字符');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_IsShow','频道是否显示','该频道是否在频道导航中显示，是为要显示，否为不显示');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0002','省份','请填写你所在的省份。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_label_out_001','导出标签','将系统后台的标签导出到服务器或者本地，以xml文件保存。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0004','民族','<P>请填写你的民族性质。</P>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0005','籍贯','请填写您的个人籍贯。如四川省成都市武侯区惠民街109号双楠嘉苑大厦A座2层1、2 号');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0006','家庭联系电话','请填写你家里的联系电话。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0007','工作电话','请填写你的工作电话。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0009','传真','请填写你的传真。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0010','QQ','请填写你的QQ。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0011','MSN','请填写你的MSN。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_safe_0004','新密码','请输入你的新密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_safe_0003','新密码确认','请再次输入你的新密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_safe_0001','密码问题','请认真填写你的密码问题，该项用于取回密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_safe_0002','密码答案','请认真填写你的密码答案，该项用于取回密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0001','锁定','锁定后该用户将无法登陆。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0005','证件','有效证件作为取回帐号的最后手段，用以核实帐号的合法身份，请您务必如实填写。<BR><SPAN class=tx>特别提醒：有效证件一旦设定，不可更改</SPAN>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0002','管理员','请你选择是不是管理员。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0004','证件类型','请你选择证件类型。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00013','登陆次数','记录你总共登陆的次数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00014','最大登陆数','记录你使用同一个IP登陆的最大数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00015','最后登陆IP','记录你最后登陆的IP。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00012','在线时长','记录你总共在线的时长。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00017','最后登陆日期','记录你最后登陆的时间日期。 ');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0006','积分','记录你的积分。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0007','G币','您的G币和当地金钱等价。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0008','魅力值','魅力值根据你被访问的次数相应的增加。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_0009','人气值','记录你被访问的次数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00010','活跃值','活跃值根据你登陆的活跃度相应增加，登陆越多越频繁活越值越高。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00011','注册日期','选择你注册的日期。 ');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0001','会员组','请填写要创建会员组的名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0002','需要积分','请设置会员要加入该会员组所需要的积分。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0003','需要G币','请设置会员要加入该会员组所需要的G币。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0004','有效期','设置该会员组的有效期。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0005','评论内容限制','设置该组会员能够发表评论内容的最大字数，如果超过这个设置的字数就会提示出错。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0006','评论审核','设置该组发表评论是否需要审核，如果需要那么评论的内容将要在后台通过审核后才能在前台看见。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0008','上传类型','设置该组会员能够上传的文件类型，用“,”半角逗号隔开。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00010','文件大小','设置该组会员上传单个文件的最大大小。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00012','最大投稿篇数','设置该组会员最多能够投稿多少篇。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00016','最大短消息数','设置该组会员能够发送短消息的最大数量。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00018','认证','注册该组会员是否需要认证，如果选择是，那么注册后只有通过认证了会员才能登陆。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00019','设置签名','设置该组的会员是否允许设置签名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00020','签名使用HTML','设置该组的会员能否使用HTML语法设置签名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00021','签名最大长度','设置该组会员能够设置签名的最大长度（字符）。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00024','删除自己主题','设置该组会员能否删除自己发的帖子。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00025','删除他人帖子','设置该组会员能否删除他人发的帖子。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00026','编辑自己帖子','设置该组会员能否编辑自己发的帖子。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00027','编辑他人帖子','设置该组会员能否编辑他人的帖子。 ');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00028','浏览发言','设置该组会员是否允许浏览其他会员的发言。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00031','解固和固顶','设置该组的会员能否设置帖子的解固和固定属性。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00032','精华帖','设置该组的会员能否设置精华帖。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00033','锁定用户','设置该组的会员能否锁定其他用户。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00035','审核主题','设置该组的会员能否审核主题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00037','奖惩','设置该组会员能否对独立的用户进行奖惩。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00038','锁定帖子','设置该组会员能否锁定/解锁其他会员的帖子。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00043','登陆积分','<DIV>设置该组会员登陆可以获得的积分和G币，格式(积分|G币)。</DIV><DIV>（10|0）表示登陆可以获得10积分和0G币</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00048','注册积分','<DIV>设置注册该组会员能够获得的积分和G币，格式(积分|G币)。</DIV><DIV>(5|0)表示注册可以获得5积分和0G币</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00044','创建社群','设置该组会员能否创建社群。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00046','社群最大人数','设置该组会员创建社群的最大加入人数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00047','创建社群最大数量','设置该组会员创建社群的最大数量。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_announce_add_0001','公告的标题','请填写公告的标题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_announce_add_0002','公告内容','请填写公告的具体内容。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_announce_add_0004','浏览会员组','请选择可以浏览该公告的会员组。 ');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_ItemCName','项目名称','分站在前台的显示名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0001','卡号','请填写你的点卡卡号/序列号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_26','栏目画中画','选择 是，则默认该栏目下的新闻可以有画中画。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0002','密码','请认真填写该点卡的密码，用于会员冲值。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_SPicURLTF','生成小图','选择生成小图，则在添加图片新闻的图片时，自动再生成一个小的图片。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_SPicURLHeight','高度','小图片的高度，单位为px，例如：100px。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_clearmessage_0001','清理原则','指删除发送方和收信方用户已经删除的短信息。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0004','点数','请认真填写该点卡的点数，用于会员冲值的多少。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_SPicURLWidth','宽度','小图片的宽度，单位为px，例如：100px。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_NaviPostion','导航','<DIV>根据导航可以连接到其他的页面。</DIV><DIV>如新浪网：</DIV><DIV>首页 | 新闻 | 财经 | 娱乐 | 视频 | 女性 | 房产</DIV><DIV>爱问 | 体育 | 科技 | 音乐 | T V | 育儿 | 家居</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_DataTable','数据库表','该频道所使用的数据库表。可根据自己需要进行修改，默认为FS_News。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0007','锁定','请设置该点卡是否已经被锁定，锁定后该点卡将不能使用。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0008','是否使用','请选择该点卡是否已经被使用，在没使用的情况下才可以买给会员使用。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_add_0009','购买','请选择该点卡是否已经卖出，如果卖出将不能再销售。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_domain','频道域名','每个频道可以绑定不同的域名，域名格式为<A href="http://www.xxxx.com">http://www.xxxx.com</A>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_metaKeywords','频道关键字','设置频道的MATA关键字，在网页的源代码里面显示，方便搜索到网页。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_metadesc','mata描述','对频道添加的MATA关键字的一个描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_00012','点卡前缀','设置要生成点卡卡号最前面的字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_isConstr','允许投稿','是否允许为该频道下的栏目投稿，打勾表示允许。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_upfiletype','允许上传格式','允许向该频道上传的文件格式。可以添加，用","半角逗号隔开。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_upfilesize','上传文件大小','允许向该频道上传文件的大小，设置的是最大值，单位为kb。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_fileDir','保存路径','设置频道在文件夹中的保存路径。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_dirrule','生成目录结构','该频道下生成保存新闻目录的结构。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_filerule','新闻命名规则','频道下添加的新闻的命名规则。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_0006','有效期','如果不填写。则过期日期为：2099-01-01 00:00:00；<BR>即理解为永不过期。正确填写格式为：2007-5-18。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_00013','密码','设置密码长度和是否用数字与字符组合。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_0003','金额','设置生成点卡所要卖的金额（元）。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_0004','点数','设置要生成的点卡的点数。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_onlinepay_0001','选择ISP商','请选择网上支付接口，必选项。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_icard_adds_10001','卡号/序列号长度','设置要生成的点卡的卡号/序列号长度。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_onlinepay_0002','网上支付帐号','指开通网上支付时，申请的帐号。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_onlinepay_0003','网上支付密码','指申请网上支付时，设置的密码必须正确。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_styleclassadd_001','样式分类','对样式的一个分类管理，便于查找和保存。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_onlinepay_0004','ISP接收页面','ISP接收页面。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_onlinepay_0005','ISP返回页面/处理页面','指网上支付平台返回处理页面。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_onlinepay_0006','MD5(其他校对)','指采用MD5加密方式进行校对。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_008','子类新闻','指此新闻下面的子类新闻，显示方式如同不规则新闻。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_MakeType','频道生成格式','<DIV>分页方式不一样。承受的负荷，生成效率也不一样。</DIV><DIV>普通：就是上一页，下一页这种。<BR>门户站的话：是按照每天来索引搜索新闻。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_base_00016','频道','请填写你所属的频道。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00017','群发','<DIV>请设置改组会员能否群发消息</DIV>0表示不支持群发，1表示支持，后面表示最多可以群发多少个用户。 <DIV>（1|10）表示支持，最多可发送10用户。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00041','积分金币兑换','<DIV>请设置改组会员能否操作积分和金币的兑换。</DIV><DIV>0为不能兑换，1为可以兑换</DIV><DIV>（0|1）表示积分不能兑换金币，金币可以兑换积分</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00042','兑换比例','<DIV>请设置改组会员的兑换比。</DIV><DIV>（100|100）表示100积分换1个金币，1个金币换100积分</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Def_Table_definedvalue','字段选项','添加的选项，只有下拉菜单，单选，多选，才有。添加格式：year|2007 前面是表单名，后面一个为表单值，如有几个字段，则用回车键隔开。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('h_jstempletclass_001','模型分类','添加js模型分类名称，1-50个字符。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('h_jstempletclass_002','上级分类','此分类的上级分类，选择根结点则为一级分类。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('h_jstempletclass_003','分类描述','<P>对js模型分类的描述，方便以后的浏览查询</P>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_FileEXName_2','新闻扩展名','选择新闻生成后的扩展名，下拉菜单中选取。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('Class_Aspx_32_02','栏目导航','在位置导航中显示的样式。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_page_add_path','单页面路径及文件名','保存该单页面的保存路径和该单页面保存的文件名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_EName_02','外部频道地址','输入外部频道的地址。如：www.xxxx.com');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_add_EName_03','附件存放地址','频道中上传的附件所存放的地址。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_TTTitle0','头条','<P>不打勾，则默认新闻为文字头条。文字头条用css控制。打勾，表示新闻为图片头条，根据程序已有的选框进行设置。</P>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_TTTitle','图片头条标题','在前台显示的图片头条新闻的标题。可以和该新闻原本的标题不一致。如不填写，则用该新闻原本的标题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_modelName','模型名称','请填写模型的名称。。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_modelItem','模型项目名称','请填写模型项目名称。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_modelDescript','模型描述','请填写模型描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_NaviContent','设置导读','添加新闻的导读。最大字符:225个中文或者英文');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_DataLib','数据库名','请填写数据库的名称，由字母和数字组成，必须以字母开头。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_upfiletype','上传类型','请设置上传的类型，用半角逗号隔开。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_upfilessize','上传的最大文件大小','请设置可以上传单个文件的大小。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_ischeck','添加信息需要审核','请选择添加该模型信息的时候是否需要审核。打钩表示需要。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_indextemplet','模型首页模版','请选择模型首页的模版。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_classtemplet','模型列表模版','请选择模型列表模版。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_newstemplet','模型内容模版','请选择模型内容显示模版。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_specialtemplet','模型专题模版','请选择模型专题模版。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_isHTML','生成静态','请选择是否生成静态，选择是表示要生成静态。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_safe_0005','旧密码','请输入你的旧密码以修改你的新密码。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_getgroupUpdate','升级','点机前面括号里红色的字，然后选择你要升级到的会员组。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_iPoint_0001','兑换G币','<DIV>点击前面括号里红色字，填写你要用多少积分兑换。</DIV>（当前兑换比例是1000积分兑换一个G币）');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_gPoint_0001','兑换积分','<DIV>点击前面红色字，填写你要用多少金币来兑换积分，</DIV><DIV>（当前兑换比例是1金币兑换1000积分）</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_getMobile_0001','绑定手机','点击前面括号中的捆绑手机，按照操作进行下一步。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_bMobile_001','输入手机/小灵通','请输入手机或小灵通号码，并选择捆绑。然后单击捆绑按钮。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('u_friendmanage_add_0002','分类说明','请填写分类说明。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('u_friendmanage_add_0001','分类名称','请填写分类名称，分类名称不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00031','真实姓名','请输入你对外的真实姓名。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00032','出生日期','请点击选择你的出生日期。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00033','会员头像','请选择你显示的头像，并输入头像的宽和高，例：100|100');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00034','用户签名','请输入你的个人签名，以便其他会员查看。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00035','爱好描述','请输入你对自己的爱好描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00036','组织关系','请输入你的组织关系，如：团员、党员……');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00037','会员职业','请输入你的职业，如：ＩＴ行业、服务行业……');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00038','性别','请输入你的性别，如：男、女');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_public_index','发布索引文件','<DIV>发布每个栏目的索引文件。方便以后搜索，归档查询之使用。</DIV><DIV><FONT color=#ff0000>只有门户版、传媒版才有此功能。</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_getContentPic','提取图片','<DIV>此功能将提取新闻内容中的您填写的第X张图片作为图片的地址。</DIV><DIV>同时此新闻将设置为图片新闻。</DIV><DIV>&nbsp;</DIV><DIV>如果新闻内容中的图片数量没有填写的数字大。将提取最后一张图片。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_getNaviContent','获取导读','自动获取新闻中的200个纯文本字符为内容导读（不包含图片地址，链接等Html标记 ）。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_site_bak','生成首页备份','<DIV>把以前的新闻首页备份到历史目录(默认为history)下的index目录。</DIV><DIV><FONT color=#ff0000>格式为：/history/index/20071215.html</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0001','会员昵称','<P>请输入你对外的的会员昵称。</P>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0008','性格描述','请输入你对自己的性格描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0012','学历','请输入你的学历，如：高中、大学、本科、硕士、博士。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0013','毕业院校','请输入你的毕业院校，如清华大学、北京大学、四川大学……');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_0014','是否结婚','请输入你的婚姻状态，如：已婚、未婚以及保密。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_userinfo_update_00015','是否开发联系方式','请选择你的联系方式是否对外开放。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Message_write_0001','会员用户名','你需要发送信息的用户名，也可以选择您好友列表里的好友。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Message_write_0002','消息标题','请输入你的信息标题。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Message_write_0003','消息内容','请输入信息的详细内容。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Message_write_0004','会员消息附件','<DIV>消息的附件地址，对方可以下载。</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Constr_0019','投稿关键字','<DIV>请输入投稿文章的关键字。</DIV><DIV>多个用"|"分开</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussManage_0001','讨论组名称','请设置你创建的讨论组的名称，不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_navimenu_pop','权限代码','请填写相应的权限代码，如果为空，则任何时候显示，否则，需要具有此权限的管理员才有权限。与管理员权限密切相关');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_News_add_naviContentTF','设置导读','当选中设置导读时，将打开新闻导读窗口，进行新闻导读的设置。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_UserParam_CommCheck','评论是否需要审核','主要是针对评论信息是否需要审核，如果选择是表示用户在前台评论后，需要通过后台会员中心评论管理通过审核后才能显示在前台。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_InsertPicPosition','画中画广告','<DIV>添加新闻的时候，如果有画中画，画中画插入新闻内容的位置。</DIV><DIV>如果新闻内容长度小于此数字，将插入最后！</DIV><DIV>格式：参数1|参数2</DIV><DIV>如：200|left</DIV><DIV><FONT color=#0000cd>参数1：为插入新闻内容的位置，单位：px</FONT></DIV><DIV><FONT color=#0000cd>参数2：为位置居左或居右。只有2个值：left,right,不能为其他值</FONT></DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussManage_0002','讨论组系统分类','由系统管理员创建讨论组分类，不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussManage_0003','讨论组子分类','指用户自行创建的讨论组分类，便于用户管理自己的讨论组。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussManage_0004','组员加入设置','请选择加入此讨论组成员的方式。如同ＱＱ的身份验证。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussManage_0007','内部公告','指本讨论组里面的内部公告。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussManage_0008','讨论组对外说明','指本讨论组，对外的描述。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussPhotoalbum_0001','相册名称','<P>只能为中文或者英文．不能出现非法字符，及符号</P>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_BaseParam_HistoryNum','归档刷新','<DIV>归档刷新索引页，最多刷新前？天的索引。范围为1-999</DIV><DIV>归档调用模板：/模板目录/Content/indexPage.html</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_Templet_Note','模板说明','<DIV>默认模板目录为:Content</DIV><DIV>首页模板:/content/index.html</DIV><DIV>栏目模板:/content/class.html</DIV><DIV>新闻模板:/content/news.html</DIV><DIV>专题模板:/content/special.html</DIV><DIV>单页面模板:/content/page.html</DIV><DIV>新闻页评论模板:/content/CommentPage.html</DIV><DIV>独立评论模板:/content/CommentList.html</DIV><DIV>每天每个栏目生成索引文件模板及归档模板:/content/indexpage.html(门户版模板)</DIV><DIV>搜索模板:/content/search.html</DIV>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0001','活动主题','请填写活动主题,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0002','活动地点','请填写活动的地点,不能为空。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0003','选择日期','请选择日期.不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0004','参与人数','请填写参与人数.为正整数.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0005','活动费用','请填写活动所需费用,为正整数.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0006','联系方式','请填写联系方式.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_discussacti_0007','活动具体方案','请填写活动的具体方案.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0001','后台管理目录','填写后台管理文件目录。默认目录为“manage”，更改了此项后需要对根目录下的“manage”这个文件进行更改才能正常访问。系统提示：如果你还不太了解系统，不建议你更改此项。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0002','后台模板目录','填写后台模板文件目录。默认目录为“Templets”，更改了此项后需要对根目录下的“Templets”这个文件进行更改才能正常访问。系统提示：如果你还不太了解系统，不建议你更改此项。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0003',' 虚拟目录','&nbsp;填写虚拟目录的路径。如：<A href="http://127.0.0.1/web">http://127.0.0.1/web</A><SPAN style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: 宋体; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana">，则此处填写“</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: Verdana">web</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: 宋体; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana">”，</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: 宋体; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana">系统提示</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: Verdana">:该项目可在根目录下更改，文件名:”Web.config”。</SPAN>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0004','配置文件管理安全码','<SPAN style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: 宋体; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana">此项填写进入配置文件管理的安全码</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: Verdana">(</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: 宋体; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana">请您务必牢记设置的安全码</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: Verdana">)</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: 宋体; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana">。系统提示：如果设置了此项</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: #2d465f; FONT-FAMILY: Verdana">,在下次设置时输入安全码出错，将不能修改系统配置文件。</SPAN>');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0005','文件上传目录','填写系统文件上传的目录。默认目录为"files"');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0009','统计系统是否使用独立数据库','请选择统计系统是否使用独立数据库，默认为否。系统提示：如果选择是，则需要数据库支持独立。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0010','资源文件管理密码','填写资源文件管理的密码(填写里请您好务必牢记)。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0013','归档表态文件存放目录','填写归档文件存放的目录。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0015','保存样式目录','填写后台管理图片调用样式目录。');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_const_0011','资源文件管理目录','请填写资源文件管理目录。默认目录为"files"');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00036','限制IP访问','请设置该组的会员能否限制IP访问.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00040','上传头像允许大小','请设置该组会员能上传头像的最大大小(KB).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00045','社群空间大小','请设置该组会员创建社群的最大空间(KB).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00039','用户选择风格','请设置该组会员能否选择自己不风格.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00030','移动他人帖子','请设置该组会员能否移动其他会员发的帖子.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00029','移动自己帖子','请设置该组会员能否移动自己的帖子.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00023','允许HTML编辑','设置该组会员在发言的时候能否用HTML语言编辑.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00022','注册多少分钟后允许发言','设置该组会员注册多少分钟后才可以发言.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00015','查看其他会员资料','请设置该组会员能否查看别人的资料.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00014','允许发表主题','请设置该组会员能否发表主题.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00013','创建讨论组','请设置该组会员能否创建讨论组.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_00011','每天最大上传数','请设置该组会员每天最大上传单个数(个).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0009','上传文件个数','请设置该组会员能够上传单个文件数(个).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_usergroup_add_0007','发表评论间隔时间','请设置该组会员发表评论间隔的时间(秒).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_ModelEItem','模型标志','不可更改，并具有唯一性，由英文、数字或下划线组成,长度3-18位');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_model_issys','模型类型','如果为<U>系统模型</U>将禁止删除，此选项不可更改');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_channelName','频道名称','请填写频道名称,该字段不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_issys','频道类型','请设置频道的类型,如果设置为系统类型,频道将不能删除.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_channelItem','项目名称','请填写项目名称,例如:频道名称为&quot;咨询中心&quot;,其项目名称为&quot;咨询&quot;');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_binddomain','捆绑域名','请填写捆绑该频道的域名(可为空).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_channelEItem','频道标识','频道的英文标识,请用英文填写(不能修改).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_channelDescript','频道描述','频道的说明和一些描述.(不能为空)');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_channelunit','频道单位','频道单位,如:篇,条.(不能为空)');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_DataLib','数据库表名','填写数据库表名,请认真填写,该项不能为空,不能保存.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_isHTML','生成静态','是否生成静态,"是"则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_htmldir','生成目录','频道生成静态的目录,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_ClassSave','栏目保存目录规则','生成栏目文件夹保存的目录规则.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_ClassFileName','栏目文件名规则','生成的栏目文件保存规则.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_SavePath','静态文件保存目录规则','静态文件保存目录规则.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_FileName','静态文件名规则','静态文件名规则.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_upfilessize','上传最大文件大小','该频道允许上传的最大文件大小(KB).');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_upfiletype','允许上传的类型','该频道允许上传文件的类型.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_ischeck','添加信息需要审核','添加信息需要审核,"需要"则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_isconstr','是否允许投稿','是否允许投稿,"允许"则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_indextemplet','模板目录','相对于整站的模板目录,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_classtemplet','频道列表模板','频道列表模板,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_newstemplet','频道内容显示模板','频道内容显示模板,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_channel_specialtemplet','频道专题模板','频道专题模板,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_ParentID','父栏目','该栏目的父栏目.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_isPage','单页面','是不是单页面,"是"则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_CName','字段中文名称','字段中文名称,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_EName','字段英文名称','字段英文名称,不能为空,不能修改.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_vType','字段类型','字段类型,不能为空,不能修改.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_vValue','默认值','设置该字段的默认值.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_vDescript','字段描述','字段的描述和说明.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_vLength','表单长度','表单长度,字段值允许的最大长度.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_isNulls','允许为空','如果允许为空,则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_isLock','是否锁定','如果锁定,则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_isUser','会员中显示此表单','会员中要显示此表单,则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_value_OrderID','权重','权重越大越靠前.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_classCName','栏目名称','栏目的名称,如"四川新闻",不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_classEName','栏目英文名','栏目英文名,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_OrderID','栏目权重','权重越大越靠前.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_Templet','栏目模板','栏目模板,不能为空.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_SavePath','栏目保存路径','栏目保存路径.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_FileName','栏目生成文件名(含扩展名)','栏目生成文件名(含扩展名),如:{@month}{@day}index.html');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_ContentTemplet','栏目下内容模板','栏目下内容模板,新闻内容的模板.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_ContentSavePath','栏目下内容保存路径规则','栏目下内容保存路径规则.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_ContentFileNameRule','栏目下内容文件名规则','栏目下内容文件名规则.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_isShowNavi','导航中显示','是否在导航中显示.是则选中.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_NaviContent','栏目导读','栏目导读.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_KeyMeta','Meta关键字','栏目关键字.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_DescMeta','Meta描述','栏目关键字的描述.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_PicURL','图片地址','代表栏目图片的地址.');
insert into [FS_Sys_Help] ([HelpID],[TitleCN],[ContentCN]) values ('H_classAdd_pop','浏览权限','浏览该栏目的权限.');